"""Alert model for fraud alerts."""

from sqlalchemy import Column, String, Text, Enum, JSON, Float, ForeignKey
from sqlalchemy.orm import relationship
import enum

from .base import BaseModel


class AlertStatus(str, enum.Enum):
    """Alert processing status."""
    RECEIVED = "received"
    PROCESSING = "processing"
    TRIAGED = "triaged"
    ESCALATED = "escalated"
    RESOLVED = "resolved"
    ERROR = "error"


class AlertType(str, enum.Enum):
    """Types of fraud alerts."""
    TRANSACTION_FRAUD = "transaction_fraud"
    ACCOUNT_TAKEOVER = "account_takeover"
    IDENTITY_THEFT = "identity_theft"
    MONEY_LAUNDERING = "money_laundering"
    SANCTIONS_VIOLATION = "sanctions_violation"
    KYC_ISSUES = "kyc_issues"
    SUSPICIOUS_ACTIVITY = "suspicious_activity"


class Alert(BaseModel):
    """Fraud alert model."""
    
    __tablename__ = "alerts"
    
    # Alert identification
    alert_id = Column(
        String(100), 
        unique=True, 
        nullable=False, 
        index=True,
        comment="Unique alert identifier from source system"
    )
    
    # Alert metadata
    alert_type = Column(
        Enum(AlertType), 
        nullable=False,
        comment="Type of fraud alert"
    )
    severity = Column(
        String(20), 
        nullable=False,
        comment="Alert severity level (critical, high, medium, low)"
    )
    source = Column(
        String(100), 
        nullable=False,
        comment="Source system that generated the alert"
    )
    source_timestamp = Column(
        String(50), 
        nullable=False,
        comment="Timestamp when alert was generated by source"
    )
    
    # Alert content
    title = Column(
        String(500), 
        nullable=False,
        comment="Alert title or summary"
    )
    description = Column(
        Text, 
        nullable=False,
        comment="Detailed alert description"
    )
    
    # Alert data
    case_data = Column(
        JSON, 
        nullable=False,
        comment="Case information for triage (JSON)"
    )
    historical_context = Column(
        JSON, 
        nullable=True,
        comment="Historical context data (JSON)"
    )
    
    # Processing metadata
    status = Column(
        Enum(AlertStatus), 
        nullable=False, 
        default=AlertStatus.RECEIVED,
        comment="Current processing status"
    )
    priority_score = Column(
        Float, 
        nullable=True,
        comment="Priority score from triage (0.0-1.0)"
    )
    risk_score = Column(
        Float, 
        nullable=True,
        comment="Risk assessment score (0.0-1.0)"
    )
    
    # Processing results
    triage_result = Column(
        JSON, 
        nullable=True,
        comment="Triage analysis results (JSON)"
    )
    processing_time_ms = Column(
        Float, 
        nullable=True,
        comment="Processing time in milliseconds"
    )
    error_message = Column(
        Text, 
        nullable=True,
        comment="Error message if processing failed"
    )
    
    # Relationships
    case_id = Column(
        String(100), 
        ForeignKey("cases.case_id"), 
        nullable=True,
        comment="Associated case identifier"
    )
    case = relationship("Case", back_populates="alerts")
    
    def __repr__(self):
        return f"<Alert(id={self.id}, alert_id={self.alert_id}, type={self.alert_type}, status={self.status})>"
